### ISSUE TITLE
Multiple cameras with no NVR

### ISSUE THREAD

**Issue by JLFN** [SaWey/home-assistant-dahua-event#3]
Guide should show like this for multi  camera

```yaml
#Dahua event listener
#https://github.com/SaWey/home-assistant-dahua-event
#IVS : Tripwire, Intrusion, Object Abandoned/Missing Advanced Intelligent Functions
#Advanced Intelligent Functions: Face Detection
#IPC-HDW4231EM-ASE
#REQUIREMENTS = ['pycurl>=7']
#########################################################################

dahua_event:
#
  - name: Laundry
    protocol: http
    host: !secret laundry_cam_ip
    port: 80
    user: !secret nvr_username
    password: !secret nvr_passsword
    events: CrossLineDetection,CrossRegionDetection,LeftDetection,TakenAwayDetection,FaceDetection
#
  - name: kitchen
    protocol: http
    host: !secret kitchen_cam_ip
    port: 80
    user: !secret nvr_username
    password: !secret nvr_passsword
    events: CrossLineDetection,CrossRegionDetection,LeftDetection,TakenAwayDetection,FaceDetection
#
  - name: Living room
    protocol: http
    host: !secret livingroom_cam_ip
    port: 80
    user: !secret nvr_username
    password: !secret nvr_passsword
    events: CrossLineDetection,CrossRegionDetection,LeftDetection,TakenAwayDetection,FaceDetection
#
  - name: Family room
    protocol: http
    host: !secret familyroom_cam_ip
    port: 80
    user: !secret nvr_username
    password: !secret nvr_passsword
    events: CrossLineDetection,CrossRegionDetection,LeftDetection,TakenAwayDetection,FaceDetection
```
